# Generated by Django 6.0.2 on 2026-02-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_car_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="palte",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
    ]
