# Generated by Django 6.0.2 on 2026-02-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_car_palte_car_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="palte",
            new_name="plate",
        ),
    ]
